### ISSUE TITLE
Crypt::OpenSSL::Bignum indirect dependency

### ISSUE THREAD

**Issue by timlegge** [timlegge/perl-Net-SAML2#24]
The tests now include an RSA key that requires Crypt::OpenSSL::RSA which requires Crypt::OpenSSL::Bignum.  Unfortunately Crypt::OpenSSL::Bignum is only recommended for   Crypt::OpenSSL::RSA

**Comment by waterkip** [comment]
This is fixed via my PR #25, I've also taken the liberty to remove the manual addition of the module from the github workflow.

**Comment by timlegge** [comment]
perfect thanks
